import React, { useState, useEffect } from "react";
import { supabase } from "@/api/supabaseClient";
import { statusColor } from "./constants";

export default function ReflectionActivity({ mod, act, sub, onUpdate, userName }) {
  const qs = act.qs || [];
  let parsedAnswers = {};
  try { parsedAnswers = JSON.parse(sub?.text || "{}"); } catch {}

  const [answers, setAnswers] = useState(parsedAnswers);
  const [revenue, setRevenue] = useState(sub?.revenue || "");
  const [oppCount, setOppCount] = useState(parsedAnswers.oppCount || "");
  const emptyOpp = () => ({ account: "", type: "", revenue: "", signal: "" });
  const parseTop3 = (raw) => {
    if (!raw) return [emptyOpp(), emptyOpp(), emptyOpp()];
    return raw.map(o => typeof o === "string" ? { account: o, type: "", revenue: "", signal: "" } : { ...emptyOpp(), ...o });
  };
  const [top3, setTop3] = useState(parseTop3(parsedAnswers.top3));
  const [loading, setLoading] = useState(false);

  // Re-sync local state when the saved submission changes (e.g. after submit/reload)
  React.useEffect(() => {
    let pa = {};
    try { pa = JSON.parse(sub?.text || "{}"); } catch {}
    setAnswers(pa);
    setRevenue(sub?.revenue || "");
    setOppCount(pa.oppCount || "");
    setTop3(parseTop3(pa.top3));
  }, [sub?.id, sub?.status]);

  const color = mod.color;
  const canSubmit = !sub?.status || sub.status === "pending" || sub.status === "needs_work";
  const spNum = typeof mod.id === "number" ? mod.id : "C";

  const handleChange = (k, v) => setAnswers(prev => ({ ...prev, [k]: v }));

  const handleOppCountChange = (v) => {
    setOppCount(v);
    const updated = { ...answers, oppCount: v, top3 };
    onUpdate({ text: JSON.stringify(updated), revenue: parseInt(revenue) || 0 });
  };

  const handleTop3Change = (i, field, v) => {
    const updated3 = top3.map((t, idx) => idx === i ? { ...t, [field]: v } : t);
    setTop3(updated3);
    const updated = { ...answers, oppCount, top3: updated3 };
    onUpdate({ text: JSON.stringify(updated), revenue: parseInt(revenue) || 0 });
  };

  const handleSubmit = async () => {
    const combined = qs.map((q, i) => `Q${i + 1}: ${answers[q.k] || ""}`).join("\n\n");
    if (!combined.replace(/Q\d: /g, "").trim()) return;
    setLoading(true);
    try {
      const feedback = await base44.integrations.Core.InvokeLLM({
        prompt: `You are a rigorous HUB SAE coach reviewing a sprint reflection. Sprint: ${mod.title}.\n\nReflection responses:\n${combined}\n\nYour job is to give SPECIFIC, HONEST coaching — not generic praise. Read the actual answers carefully.\n\nRespond ONLY in JSON with exactly these three fields:\n{\n  "strengths": "2-3 sentences citing SPECIFIC things they wrote that show real insight or self-awareness. Quote or reference their actual words. If their answers are vague or thin, say so honestly.",\n  "growth": "2-3 sentences identifying SPECIFIC gaps in their thinking based on what they wrote. Call out where they were surface-level, avoided accountability, or missed the deeper insight. Name the exact question or moment where the gap appeared.",\n  "coaching": "1-2 sentences of a direct, challenging coaching note — something they need to hear that will actually change how they show up in the next sprint. Not a compliment. A push."\n}`,
        response_json_schema: {
          type: "object", properties: {
            strengths: { type: "string" }, growth: { type: "string" }, coaching: { type: "string" }
          }
        }
      });
      const f = typeof feedback === "object" && feedback.strengths ? feedback : { strengths: "Your reflection has been received.", growth: "", coaching: "Keep going — each sprint builds on the last." };
      onUpdate({ text: JSON.stringify({ ...answers, oppCount, top3 }), revenue: parseInt(revenue) || 0, feedback: f, status: "approved" });
    } catch { }
    setLoading(false);
  };

  const handleDownload = () => {
    const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
    const lines = ["HUB SAE GROWTH ENGINE", `Sprint ${spNum} Reflection — ${mod.title}`, "═".repeat(60), `SAE: ${userName}`, `Date: ${date}`, "", "─".repeat(60), "SPRINT REFLECTION", "─".repeat(60), ""];
    qs.forEach((q, i) => { lines.push(q.l, "", answers[q.k] || "[No response entered]", ""); if (i < qs.length - 1) lines.push("─".repeat(40), ""); });
    lines.push("─".repeat(60), "REVENUE INFLUENCED", "─".repeat(60), "", `$${(parseInt(revenue) || 0).toLocaleString()}`, "");
    if (sub?.score) lines.push("─".repeat(60), "AI REVIEW", "─".repeat(60), "", `Score: ${sub.score}/10 — ${sub.feedback?.verdict || ""}`, `Strengths: ${sub.feedback?.strengths || ""}`, sub.feedback?.gaps ? `Gaps: ${sub.feedback.gaps}` : "", `Coaching: ${sub.feedback?.coaching || ""}`, "");
    lines.push("─".repeat(60), "Generated by HUB SAE Growth Engine");
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = `Sprint${spNum}_Reflection_${(userName || "SAE").replace(/\s+/g, "_")}_${new Date().toISOString().slice(0, 10)}.txt`;
    document.body.appendChild(a); a.click(); document.body.removeChild(a); URL.revokeObjectURL(url);
  };

  return (
    <div style={{ padding: 24, maxWidth: 760, margin: "0 auto", width: "100%" }}>
      <div style={{ background: "#fff", border: "1px solid #D1D9E0", borderRadius: 14, padding: 20, marginBottom: 16 }}>
        <div style={{ fontSize: 10, fontWeight: 800, color, textTransform: "uppercase", letterSpacing: ".08em", marginBottom: 6 }}>✍️ Sprint Reflection</div>
        <div style={{ fontSize: 16, fontWeight: 900, color: "#18252D", marginBottom: 4 }}>Sprint {spNum} Reflection</div>
        <div style={{ fontSize: 12, color: "#385263", lineHeight: 1.6 }}>Answer each question honestly and specifically — name the account, the moment, the conversation.</div>
        <div style={{ marginTop: 12, background: "#EEF0E2", borderRadius: 8, padding: "10px 14px", fontSize: 12, color: "#385263", lineHeight: 1.6, border: "1px solid #D1D9E0" }}>
          <strong style={{ color: "#18252D" }}>How to submit:</strong> Complete all questions below, then click <strong>"Submit Reflection for AI Review"</strong>. Once reviewed, click <strong>"Download as .txt"</strong> to save your reflection, then use the <strong>"Upload to SharePoint"</strong> button to submit it for the record.
        </div>
      </div>
      {qs.map(q => (
        <div key={q.k} style={{ background: "#fff", border: "1px solid #D1D9E0", borderRadius: 12, padding: 18, marginBottom: 12 }}>
          <div style={{ fontSize: 12, fontWeight: 700, color: "#18252D", lineHeight: 1.5, marginBottom: 10 }}>{q.l}</div>
          <textarea rows={4} value={answers[q.k] || ""} onChange={e => handleChange(q.k, e.target.value)}
            placeholder="Be specific — name the account, the moment, the conversation."
            style={{ width: "100%", background: "#EEF0E2", border: "1px solid #D1D9E0", borderRadius: 8, padding: "12px 14px", fontSize: 12, color: "#18252D", lineHeight: 1.6, resize: "vertical", outline: "none", fontFamily: "inherit", boxSizing: "border-box" }} />
        </div>
      ))}
      <div style={{ background: "#fff", border: `2px solid ${color}30`, borderRadius: 12, padding: 18, marginBottom: 12 }}>
        <div style={{ fontSize: 12, fontWeight: 800, color, textTransform: "uppercase", letterSpacing: ".06em", marginBottom: 4 }}>💰 Revenue Influenced This Sprint</div>
        <div style={{ fontSize: 12, color: "#385263", marginBottom: 12, lineHeight: 1.5 }}>Total revenue you influenced within your managed book this sprint.</div>
        <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 16 }}>
          <span style={{ fontSize: 18, color: "#757584", fontWeight: 700 }}>$</span>
          <input type="number" value={revenue} onChange={e => setRevenue(e.target.value)} placeholder="0"
            style={{ width: 160, background: "#EEF0E2", border: "1px solid #D1D9E0", borderRadius: 8, padding: "10px 14px", fontSize: 16, fontWeight: 700, outline: "none", fontFamily: "inherit" }} />
          <span style={{ fontSize: 12, color: "#757584" }}>total revenue influenced this sprint</span>
        </div>
        <div style={{ borderTop: "1px solid #E3E3E3", paddingTop: 14 }}>
          <div style={{ fontSize: 12, fontWeight: 800, color, textTransform: "uppercase", letterSpacing: ".06em", marginBottom: 4 }}>🎯 Opportunities Uncovered This Sprint</div>
          <div style={{ fontSize: 12, color: "#385263", marginBottom: 10, lineHeight: 1.5 }}>How many new opportunities did you uncover this sprint?</div>
          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <input type="number" value={oppCount} onChange={e => handleOppCountChange(e.target.value)} placeholder="0"
              style={{ width: 100, background: "#EEF0E2", border: "1px solid #D1D9E0", borderRadius: 8, padding: "10px 14px", fontSize: 16, fontWeight: 700, outline: "none", fontFamily: "inherit" }} />
            <span style={{ fontSize: 12, color: "#757584" }}>opportunities uncovered this sprint</span>
          </div>
        </div>
      </div>
      <div style={{ background: "#fff", border: `2px solid ${color}30`, borderRadius: 12, padding: 18, marginBottom: 16 }}>
        <div style={{ fontSize: 12, fontWeight: 800, color, textTransform: "uppercase", letterSpacing: ".06em", marginBottom: 4 }}>🏆 Top 3 Opportunities Uncovered</div>
        <div style={{ fontSize: 12, color: "#385263", marginBottom: 14, lineHeight: 1.5 }}>Log your top 3 opportunities using the structured format below.</div>
        {[0, 1, 2].map(i => (
          <div key={i} style={{ border: "1px solid #D1D9E0", borderRadius: 10, padding: 14, marginBottom: 10, background: "#FAFBFC" }}>
            <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 10 }}>
              <div style={{ width: 22, height: 22, borderRadius: 6, background: color, color: "#fff", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: 800, fontSize: 11, flexShrink: 0 }}>{i + 1}</div>
              <span style={{ fontSize: 11, fontWeight: 700, color: "#757584", textTransform: "uppercase", letterSpacing: ".06em" }}>Opportunity {i + 1}</span>
            </div>
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8 }}>
              <div>
                <div style={{ fontSize: 10, fontWeight: 700, color: "#757584", marginBottom: 4, textTransform: "uppercase" }}>Account Name</div>
                <input value={top3[i]?.account || ""} onChange={e => handleTop3Change(i, "account", e.target.value)}
                  placeholder="e.g. Meridian Logistics"
                  style={{ width: "100%", background: "#EEF0E2", border: "1px solid #D1D9E0", borderRadius: 7, padding: "8px 10px", fontSize: 12, outline: "none", fontFamily: "inherit", boxSizing: "border-box" }} />
              </div>
              <div>
                <div style={{ fontSize: 10, fontWeight: 700, color: "#757584", marginBottom: 4, textTransform: "uppercase" }}>Opportunity Type</div>
                <select value={top3[i]?.type || ""} onChange={e => handleTop3Change(i, "type", e.target.value)}
                  style={{ width: "100%", background: "#EEF0E2", border: "1px solid #D1D9E0", borderRadius: 7, padding: "8px 10px", fontSize: 12, outline: "none", fontFamily: "inherit", boxSizing: "border-box" }}>
                  <option value="">Select type…</option>
                  <option value="Cyber">Cyber</option>
                  <option value="EPLI">EPLI</option>
                  <option value="D&O">D&O</option>
                  <option value="Workers Comp">Workers Comp</option>
                  <option value="Commercial Auto">Commercial Auto</option>
                  <option value="Property">Property</option>
                  <option value="GL">General Liability</option>
                  <option value="Umbrella">Umbrella / Excess</option>
                  <option value="Benefits">Employee Benefits</option>
                  <option value="Life / Disability">Life / Disability</option>
                  <option value="Financial Lines">Financial Lines</option>
                  <option value="Other">Other</option>
                </select>
              </div>
              <div>
                <div style={{ fontSize: 10, fontWeight: 700, color: "#757584", marginBottom: 4, textTransform: "uppercase" }}>Est. Revenue</div>
                <div style={{ display: "flex", alignItems: "center", gap: 4 }}>
                  <span style={{ fontSize: 13, color: "#757584" }}>$</span>
                  <input value={top3[i]?.revenue || ""} onChange={e => handleTop3Change(i, "revenue", e.target.value)}
                    placeholder="e.g. 28,000"
                    style={{ flex: 1, background: "#EEF0E2", border: "1px solid #D1D9E0", borderRadius: 7, padding: "8px 10px", fontSize: 12, outline: "none", fontFamily: "inherit" }} />
                </div>
              </div>
              <div>
                <div style={{ fontSize: 10, fontWeight: 700, color: "#757584", marginBottom: 4, textTransform: "uppercase" }}>Signal / Reason</div>
                <input value={top3[i]?.signal || ""} onChange={e => handleTop3Change(i, "signal", e.target.value)}
                  placeholder="e.g. No cyber coverage despite WMS platform"
                  style={{ width: "100%", background: "#EEF0E2", border: "1px solid #D1D9E0", borderRadius: 7, padding: "8px 10px", fontSize: 12, outline: "none", fontFamily: "inherit", boxSizing: "border-box" }} />
              </div>
            </div>
          </div>
        ))}
      </div>
      {canSubmit && (
        <button onClick={handleSubmit} disabled={loading}
          style={{ width: "100%", padding: 14, borderRadius: 10, border: "none", fontWeight: 800, fontSize: 14, marginBottom: 12, cursor: "pointer", background: loading ? "#E3E3E3" : color, color: loading ? "#757584" : "#fff" }}>
          {loading ? "Claude is reviewing…" : "Submit Reflection for AI Review"}
        </button>
      )}
      <div style={{ display: "flex", gap: 8, marginBottom: 12, flexWrap: "wrap" }}>
        <button onClick={handleDownload} style={{ display: "inline-flex", alignItems: "center", gap: 6, padding: "10px 16px", borderRadius: 8, border: "none", fontWeight: 700, fontSize: 12, cursor: "pointer", background: "#EEF0E2", color: "#18252D" }}>⬇ Download as .txt</button>
        {act.spUrl && (
          <a href={act.spUrl} target="_blank" rel="noreferrer" style={{ display: "inline-flex", alignItems: "center", gap: 6, padding: "10px 16px", borderRadius: 8, border: "none", fontWeight: 700, fontSize: 12, cursor: "pointer", textDecoration: "none", background: "#0078D4", color: "#fff" }}>
            📄 Upload to SharePoint — Sprint {spNum}
          </a>
        )}
      </div>
      {sub?.feedback && sub.status !== "pending" && (
        <div style={{ background: "#fff", border: `2px solid ${color}30`, borderRadius: 14, overflow: "hidden" }}>
          <div style={{ padding: "14px 18px", background: color + "10", borderBottom: "1px solid #D1D9E0" }}>
            <div style={{ fontWeight: 800, color, fontSize: 14 }}>Coach Feedback</div>
            <div style={{ fontSize: 11, color: "#757584", marginTop: 2 }}>Reflection received — here's your coaching for this sprint.</div>
          </div>
          <div style={{ padding: 18, display: "flex", flexDirection: "column", gap: 12 }}>
            {sub.feedback.strengths && <div style={{ background: "#d1fae5", border: "1px solid #3EBD3E40", borderRadius: 8, padding: 14 }}><div style={{ fontSize: 10, fontWeight: 800, color: "#3EBD3E", textTransform: "uppercase", marginBottom: 4 }}>What's Showing Up Well</div><p style={{ fontSize: 12, lineHeight: 1.6, margin: 0 }}>{sub.feedback.strengths}</p></div>}
            {sub.feedback.growth && <div style={{ background: "#fef9ec", border: "1px solid #F3B92140", borderRadius: 8, padding: 14 }}><div style={{ fontSize: 10, fontWeight: 800, color: "#c9941a", textTransform: "uppercase", marginBottom: 4 }}>Areas to Grow Into</div><p style={{ fontSize: 12, lineHeight: 1.6, margin: 0 }}>{sub.feedback.growth}</p></div>}
            {sub.feedback.coaching && <div style={{ background: color + "10", border: `1px solid ${color}30`, borderRadius: 8, padding: 14 }}><div style={{ fontSize: 10, fontWeight: 800, color, textTransform: "uppercase", marginBottom: 4 }}>Coach's Note</div><p style={{ fontSize: 12, lineHeight: 1.6, margin: 0 }}>{sub.feedback.coaching}</p></div>}
          </div>
        </div>
      )}
    </div>
  );
}