import React, { useState, useEffect } from "react";
import { supabase } from "@/api/supabaseClient";
import { statusColor } from "./constants";

export default function StandardActivity({ mod, act, sub, onUpdate, allSubs, userName }) {
  const [text, setText] = useState(sub?.text || "");
  const [revenue, setRevenue] = useState(sub?.revenue || "");
  const [checks, setChecks] = useState(() => {
    try { return JSON.parse(sub?.checkState || "{}"); } catch { return {}; }
  });
  const [loading, setLoading] = useState(false);

  // Re-sync local state when the saved submission changes (e.g. after submit/reload)
  useEffect(() => {
    setText(sub?.text || "");
    setRevenue(sub?.revenue || "");
    try { setChecks(JSON.parse(sub?.checkState || "{}")); } catch { setChecks({}); }
  }, [sub?.id, sub?.status]);

  const color = mod.color;
  const scol = statusColor(sub?.status);
  const canSubmit = !sub?.status || sub.status === "pending" || sub.status === "needs_work";
  const showRevenue = !act.noRevenue;

  const handleCompileDownload = () => {
    const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
    const saeLabel = userName || "SAE";
    const lines = [
      "HUB SAE GROWTH ENGINE",
      "CAPSTONE: STRATEGIC ACCOUNT DOSSIER",
      "═".repeat(60),
      `SAE: ${saeLabel}`,
      `Date: ${date}`,
      "",
    ];
    const sections = [
      { id: "c-1", title: "Account Selection & Rationale" },
      { id: "c-2", title: "Dossier Section 1: Opportunity Map" },
      { id: "c-3", title: "Dossier Section 2: Diagnostic Intelligence" },
      { id: "c-4", title: "Dossier Section 3: Recommendation Delivered" },
      { id: "c-5", title: "Dossier Section 4: Cross-Sell Execution" },
      { id: "c-6", title: "Dossier Section 5: Renewal Strategy" },
      { id: "c-7", title: "Dossier Section 6: Executive Relationship" },
      { id: "c-9", title: "Forward Commitments" },
    ];
    sections.forEach(s => {
      const sData = allSubs?.[s.id];
      lines.push("─".repeat(60));
      lines.push(s.title.toUpperCase());
      lines.push("─".repeat(60));
      lines.push(sData?.text ? sData.text : "[Not yet completed]");
      lines.push("");
    });
    lines.push("─".repeat(60));
    lines.push("Generated by HUB SAE Growth Engine");
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `Capstone_Dossier_${saeLabel.replace(/\s+/g, "_")}_${new Date().toISOString().slice(0, 10)}.txt`;
    document.body.appendChild(a); a.click(); document.body.removeChild(a);
    URL.revokeObjectURL(url);
    onUpdate({ text: "Dossier downloaded", revenue: 0, score: 8, feedback: { verdict: "Strong", strengths: "Dossier compiled and downloaded for submission.", gaps: "", coaching: "Upload the downloaded file to the SharePoint link to complete your submission." }, status: "approved" });
  };

  const handleSubmit = async () => {
    const submitText = act.isChecklist
      ? (act.checks || []).map(c => `${c.lbl}: ${checks[c.id] ? "✓ Completed" : "Not yet completed"}`).join("\n")
      : text;
    if (!act.isChecklist && !text.trim()) return;
    setLoading(true);
    // Send notification email when checklist (capstone final) is submitted
    if (act.isChecklist) {
      try {
        await base44.integrations.Core.SendEmail({
          to: "tori.manganelli@hubinternational.com",
          subject: "Capstone Submission Notification",
          body: `${userName || "An SAE"} has submitted their Capstone. Please review their dossier and schedule their presentation review.`
        });
      } catch (e) { console.error("Failed to send notification email", e); }
    }
    try {
      const res = await base44.integrations.Core.InvokeLLM({
        prompt: `You are a HUB SAE coach. Sprint: ${mod.title}. Activity: ${act.lbl}. Criteria: ${act.sg}.\n\nSAE submission:\n${submitText}\n\nRespond ONLY in JSON: {"score": number 1-10, "verdict": "Strong|Adequate|Needs Work", "strengths": "string", "gaps": "string", "coaching": "string"}`,
        response_json_schema: {
          type: "object",
          properties: {
            score: { type: "number" },
            verdict: { type: "string" },
            strengths: { type: "string" },
            gaps: { type: "string" },
            coaching: { type: "string" }
          }
        }
      });
      const feedback = typeof res === "object" && res.score ? res : { score: 5, verdict: "Adequate", strengths: "Received.", gaps: "", coaching: "Review and resubmit." };
      const status = feedback.score >= 7 ? "approved" : feedback.score >= 5 ? "adequate" : "needs_work";
      onUpdate({ text: act.isChecklist ? JSON.stringify(checks) : text, checkState: act.isChecklist ? JSON.stringify(checks) : undefined, revenue: showRevenue ? (parseInt(revenue) || 0) : 0, score: feedback.score, feedback, status });
    } catch { }
    setLoading(false);
  };

  const toggleCheck = (id) => setChecks(prev => ({ ...prev, [id]: !prev[id] }));
  const allChecked = true; // checklist always submittable

  const handleChecklistComplete = async () => {
    setLoading(true);
    try {
      await base44.integrations.Core.SendEmail({
        to: "tori.manganelli@hubinternational.com",
        subject: "Capstone Presentation Checklist Completed",
        body: `${userName || "An SAE"} has marked their Presentation & Advancement Checklist as complete.`
      });
    } catch (e) { console.error("Failed to send notification email", e); }
    onUpdate({ text: JSON.stringify(checks), checkState: JSON.stringify(checks), revenue: 0, status: "approved" });
    setLoading(false);
  };

  return (
    <div style={{ padding: 24, maxWidth: 760, margin: "0 auto", width: "100%" }}>
      <div style={{ background: "#fff", border: "1px solid #D1D9E0", borderRadius: 14, padding: 20, marginBottom: 16, display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 12 }}>
        <div>
          <div style={{ fontSize: 10, fontWeight: 800, color, textTransform: "uppercase", letterSpacing: ".08em", marginBottom: 6 }}>🛠 Activity</div>
          <div style={{ fontSize: 16, fontWeight: 900, color: "#18252D" }}>{act.lbl}</div>
        </div>
        {sub?.status && sub.status !== "pending" && !act.isChecklist && (
          <div style={{ background: scol + "15", border: `2px solid ${scol}40`, borderRadius: 10, padding: "8px 14px", textAlign: "center", flexShrink: 0 }}>
            <div style={{ fontSize: 20, fontWeight: 900, color: scol }}>{sub.score}/10</div>
            <div style={{ fontSize: 10, fontWeight: 700, color: scol }}>{sub.feedback?.verdict}</div>
          </div>
        )}
      </div>

      {act.instructions && (
        <div style={{ background: color + "08", border: `1px solid ${color}20`, borderRadius: 10, padding: 14, marginBottom: 16 }}>
          <div style={{ fontSize: 10, fontWeight: 700, color, marginBottom: 4, textTransform: "uppercase" }}>What to Do</div>
          <p style={{ fontSize: 12, color: "#385263", margin: 0, lineHeight: 1.6 }}>{act.instructions}</p>
        </div>
      )}

      <div style={{ background: color + "06", border: `1px solid ${color}15`, borderRadius: 10, padding: 14, marginBottom: 16 }}>
        <div style={{ fontSize: 10, fontWeight: 700, color, marginBottom: 4, textTransform: "uppercase" }}>Scoring Criteria</div>
        <p style={{ fontSize: 12, color: "#385263", margin: 0, lineHeight: 1.6 }}>{act.sg}</p>
      </div>

      {act.isCompile ? (
        <div style={{ background: "#fff", border: "1px solid #D1D9E0", borderRadius: 12, padding: 24, marginBottom: 16 }}>
          <div style={{ fontSize: 13, fontWeight: 700, color: "#18252D", marginBottom: 12 }}>Your complete Capstone Dossier will be compiled from all sections above into a single document.</div>
          <div style={{ marginBottom: 16 }}>
            {[
              { id: "c-1", title: "Account Selection & Rationale" },
              { id: "c-2", title: "Dossier Section 1: Opportunity Map" },
              { id: "c-3", title: "Dossier Section 2: Diagnostic Intelligence" },
              { id: "c-4", title: "Dossier Section 3: Recommendation Delivered" },
              { id: "c-5", title: "Dossier Section 4: Cross-Sell Execution" },
              { id: "c-6", title: "Dossier Section 5: Renewal Strategy" },
              { id: "c-7", title: "Dossier Section 6: Executive Relationship" },
              { id: "c-9", title: "Forward Commitments" },
            ].map(s => {
              const done = !!allSubs?.[s.id]?.text;
              return (
                <div key={s.id} style={{ display: "flex", alignItems: "center", gap: 10, padding: "7px 0", borderBottom: "1px solid #F0F0F0" }}>
                  <div style={{ width: 18, height: 18, borderRadius: 5, background: done ? "#3EBD3E" : "#E3E3E3", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
                    {done && <span style={{ color: "#fff", fontSize: 11, fontWeight: 900 }}>✓</span>}
                  </div>
                  <span style={{ fontSize: 12, color: done ? "#18252D" : "#757584" }}>{s.title}</span>
                </div>
              );
            })}
          </div>
          <div style={{ background: "#EEF0E2", borderRadius: 8, padding: 12, fontSize: 12, color: "#385263", lineHeight: 1.6, marginBottom: 16 }}>
            <strong>How to submit:</strong> Click <strong>"Download Full Dossier (.txt)"</strong> to save your complete document. Then click <strong>"Upload to SharePoint"</strong> to submit it officially. Both steps are required.
          </div>
          <div style={{ background: "#fff8e1", border: "1px solid #F3B92140", borderRadius: 8, padding: 12, fontSize: 12, color: "#385263", lineHeight: 1.6, marginBottom: 16 }}>
            <strong>📊 Create Your Presentation:</strong> Upload your downloaded dossier into <a href="https://claude.ai" target="_blank" rel="noreferrer" style={{ color: "#0678D5", fontWeight: 700 }}>Claude.ai</a> and ask it to <strong>"Create a PowerPoint presentation with a maximum of 6 slides based on this dossier."</strong> Use the generated slides for your live capstone presentation.
          </div>
          <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>
            <button onClick={handleCompileDownload}
              style={{ display: "inline-flex", alignItems: "center", gap: 8, padding: "12px 20px", borderRadius: 10, border: "none", fontWeight: 800, fontSize: 13, cursor: "pointer", background: color, color: "#fff" }}>
              ⬇ Download Full Dossier (.txt)
            </button>
            <a href={act.spUrl} target="_blank" rel="noreferrer"
              style={{ display: "inline-flex", alignItems: "center", gap: 8, padding: "12px 20px", borderRadius: 10, fontWeight: 800, fontSize: 13, textDecoration: "none", background: "#0078D4", color: "#fff" }}>
              📄 Upload to SharePoint
            </a>
          </div>
        </div>
      ) : act.isChecklist ? (
        <div style={{ marginBottom: 16 }}>
          <div style={{ background: "#fff", border: "1px solid #D1D9E0", borderRadius: 12, padding: 24, marginBottom: 12, textAlign: "center" }}>
            <div style={{ fontSize: 32, marginBottom: 12 }}>📅</div>
            <div style={{ fontSize: 15, fontWeight: 900, color: "#18252D", marginBottom: 8 }}>Schedule Your Capstone Presentation</div>
            <div style={{ fontSize: 13, color: "#385263", lineHeight: 1.6, marginBottom: 20 }}>
              Book your 45-minute live presentation with the HUB Sales Force Development team. You'll walk through your full Strategic Account Dossier and complete Q&A with the panel.
            </div>
            <a
              href="https://outlook.office.com/bookwithme/user/64ad068b94944190b7b4a72b4d71faed@hubinternational.com/meetingtype/ANN4NEpWVkO-5q0Fo9Cz0g2?anonymous&ep=mlink"
              target="_blank"
              rel="noreferrer"
              style={{ display: "inline-flex", alignItems: "center", gap: 10, background: color, color: "#fff", padding: "14px 28px", borderRadius: 10, fontWeight: 800, fontSize: 14, textDecoration: "none" }}
            >
              📅 Book Your Capstone Presentation →
            </a>
          </div>
          <div style={{ background: checks["survey_completed"] ? "#f0fdf4" : "#fff8e1", border: `2px solid ${checks["survey_completed"] ? "#3EBD3E" : "#F3B921"}`, borderRadius: 12, padding: 24 }}>
            <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 8 }}>
              <div style={{ fontSize: 24 }}>📋</div>
              <div>
                <div style={{ fontSize: 14, fontWeight: 900, color: "#18252D" }}>Required: Program Feedback Survey</div>
                <div style={{ fontSize: 11, color: "#757584" }}>Must be completed before submitting your capstone</div>
              </div>
              {checks["survey_completed"] && <span style={{ marginLeft: "auto", fontSize: 11, fontWeight: 800, color: "#3EBD3E", background: "#d1fae5", padding: "4px 10px", borderRadius: 99 }}>✓ Completed</span>}
            </div>
            <div style={{ fontSize: 12, color: "#385263", lineHeight: 1.6, marginBottom: 16 }}>
              Please complete the program feedback survey. Your input helps us improve the HUB SAE Growth Engine for future participants.
            </div>
            <div style={{ display: "flex", gap: 10, flexWrap: "wrap", alignItems: "center" }}>
              <a
                href="https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=whWFoZgxrU-X7SmkbJdP2-m45qkl79RDv7dXj0fAeH9UQ1BJTEZKQUc0QlJFMTJLVVJOQkFKRkxGUC4u"
                target="_blank"
                rel="noreferrer"
                style={{ display: "inline-flex", alignItems: "center", gap: 8, background: "#0078D4", color: "#fff", padding: "12px 20px", borderRadius: 8, fontWeight: 800, fontSize: 13, textDecoration: "none" }}
              >
                📋 Open Survey →
              </a>
              {!checks["survey_completed"] && (
                <button
                  onClick={() => setChecks(prev => ({ ...prev, survey_completed: true }))}
                  style={{ padding: "12px 20px", borderRadius: 8, border: `2px solid #3EBD3E`, background: "transparent", color: "#3EBD3E", fontWeight: 800, fontSize: 13, cursor: "pointer" }}
                >
                  ✓ I've Completed the Survey
                </button>
              )}
            </div>
          </div>
        </div>
      ) : (
        <textarea
          rows={8} value={text} onChange={e => setText(e.target.value)}
          placeholder="Describe what you did, what the client said, and what you learned. Be specific."
          style={{ width: "100%", background: "#EEF0E2", border: "1px solid #D1D9E0", borderRadius: 10, padding: "14px 16px", fontSize: 13, color: "#18252D", lineHeight: 1.7, resize: "vertical", outline: "none", marginBottom: 16, display: "block", fontFamily: "inherit", boxSizing: "border-box" }}
        />
      )}

      {showRevenue && (
        <div style={{ background: "#fff", border: "1px solid #D1D9E0", borderRadius: 12, padding: 16, marginBottom: 16 }}>
          <div style={{ fontSize: 12, fontWeight: 700, color: "#18252D", marginBottom: 8 }}>
            {act.revenueLabel || "Revenue Influenced"} <span style={{ color: "#757584", fontWeight: 400 }}>(self-report)</span>
          </div>
          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <span style={{ fontSize: 16, color: "#757584" }}>$</span>
            <input type="number" value={revenue} onChange={e => setRevenue(e.target.value)} placeholder="0"
              style={{ width: 140, background: "#EEF0E2", border: "1px solid #D1D9E0", borderRadius: 8, padding: "10px 14px", fontSize: 14, fontWeight: 700, outline: "none", fontFamily: "inherit" }} />
            <span style={{ fontSize: 12, color: "#757584" }}>estimated revenue influenced</span>
          </div>
        </div>
      )}

      {canSubmit && !act.isChecklist && (
        <button onClick={handleSubmit} disabled={loading}
          style={{ width: "100%", padding: 14, borderRadius: 10, border: "none", fontWeight: 800, fontSize: 14, marginBottom: 12, cursor: "pointer", background: loading ? "#E3E3E3" : color, color: loading ? "#757584" : "#fff" }}>
          {loading ? "Reviewing…" : "Submit for AI Review"}
        </button>
      )}

      {canSubmit && act.isChecklist && (
        <>
          {!checks["survey_completed"] && (
            <div style={{ background: "#fff8e1", border: "1px solid #F3B921", borderRadius: 8, padding: 12, marginBottom: 12, fontSize: 12, color: "#7a5c00", fontWeight: 600, textAlign: "center" }}>
              ⚠️ Please complete the required feedback survey above before submitting.
            </div>
          )}
          <button onClick={handleChecklistComplete} disabled={loading || !checks["survey_completed"]}
            style={{ width: "100%", padding: 14, borderRadius: 10, border: "none", fontWeight: 800, fontSize: 14, marginBottom: 12, cursor: (loading || !checks["survey_completed"]) ? "default" : "pointer", background: (loading || !checks["survey_completed"]) ? "#E3E3E3" : color, color: (loading || !checks["survey_completed"]) ? "#757584" : "#fff" }}>
            {loading ? "Submitting…" : "Submit Complete"}
          </button>
        </>
      )}

      {!act.isChecklist && sub?.feedback && sub.status !== "pending" && <FeedbackCard sub={sub} color={color} scol={scol} onReset={() => onUpdate({ ...sub, status: "pending", score: null, feedback: null })} />}
    </div>
  );
}

function FeedbackCard({ sub, color, scol, onReset }) {
  return (
    <div style={{ background: "#fff", border: `2px solid ${scol}40`, borderRadius: 14, overflow: "hidden" }}>
      <div style={{ padding: "14px 18px", background: scol + "12", borderBottom: "1px solid #D1D9E0", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <div style={{ fontWeight: 800, color: scol, fontSize: 14 }}>AI Review — {sub.feedback.verdict}</div>
        <div style={{ fontSize: 20, fontWeight: 900, color: scol }}>{sub.score}/10</div>
      </div>
      <div style={{ padding: 18, display: "flex", flexDirection: "column", gap: 12 }}>
        {sub.feedback.strengths && <div style={{ background: "#d1fae5", border: "1px solid #3EBD3E40", borderRadius: 8, padding: 14 }}><div style={{ fontSize: 10, fontWeight: 800, color: "#3EBD3E", textTransform: "uppercase", marginBottom: 4 }}>What's Working</div><p style={{ fontSize: 12, lineHeight: 1.6, margin: 0 }}>{sub.feedback.strengths}</p></div>}
        {sub.feedback.gaps && <div style={{ background: "#fee2e2", border: "1px solid #AC153440", borderRadius: 8, padding: 14 }}><div style={{ fontSize: 10, fontWeight: 800, color: "#AC1534", textTransform: "uppercase", marginBottom: 4 }}>Gaps to Address</div><p style={{ fontSize: 12, lineHeight: 1.6, margin: 0 }}>{sub.feedback.gaps}</p></div>}
        {sub.feedback.coaching && <div style={{ background: color + "10", border: `1px solid ${color}30`, borderRadius: 8, padding: 14 }}><div style={{ fontSize: 10, fontWeight: 800, color, textTransform: "uppercase", marginBottom: 4 }}>Coach's Note</div><p style={{ fontSize: 12, lineHeight: 1.6, margin: 0 }}>{sub.feedback.coaching}</p></div>}
        {sub.status === "needs_work" && <button onClick={onReset} style={{ padding: "10px 16px", borderRadius: 8, background: "transparent", border: `2px solid ${color}`, color, fontWeight: 700, fontSize: 12, cursor: "pointer" }}>Revise and Resubmit</button>}
      </div>
    </div>
  );
}